# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
pod 'SDWebImage', '~> 5.0.0-beta3'
pod 'AFNetworkActivityLogger', '~> 3.0.0'
pod 'MYToolKit', '~> 0.0.4'
pod 'MJRefresh', '~> 3.1.15.7'
  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
